### ISSUE TITLE
Setting a public teleport with the same name as private teleports overrules the private teleports

### ISSUE THREAD

**Issue by IamGimli** [CatalysmsServerManager/7-days-to-die-server-manager#291]
**Describe the bug**
When creating private teleports, names aren't validated against other private teleports so multiple players can have teleports with the same generic name (like "base" or "home").
If one of those players then makes their generic-named teleport public, no error is generated and all other players will teleport to the public location instead of their private one named the same. 
A malicious user can create the public teleport 180 blocks above ground to kill every other player using the generically-named teleport.

**To Reproduce**
1. Have multiple players create a teleport using the same generic name (teleset home)
2. Have one of those players make their home teleport public (telepublic home)
3. Watch as every player with a private teleport named home teleport to the location of the public teleport instead of their private home.

**Expected behavior**
When making a teleport public, there should be an error if the same name exists in any other player's private teleport list.
Alternately, private teleports should always overrule public teleports when name conflicts occur.

**7 days to die server info:**
 - Output of the `version` command:
Game version: Alpha 19 (b180) Compatibility Version: Alpha 19
Mod Allocs command extensions: 20
Mod Allocs server fixes: 23
Mod Allocs MapRendering and Webinterface: 35

**Comment by niekcandaele** [comment]
Thank you for the detailed report!

> private teleports should always overrule public teleports when name conflicts occur.

Seems like the best option

**Comment by IamGimli** [comment]
I've looked at the code in \api\hooks\sdtdCommands\commands\tele.js and I'm wondering if reversing the order in which the serverTeleportsFound variable is constructed from "let serverTeleportsFound = playerTeleports.concat(publicTeleports);" to "let serverTeleportsFound = publicTeleports.concat(playerTeleports);" would be the easy way to implement this change.

I looked into how the "_.uniq" function works and it's supposed to keep the first instance of the duplicate value in the array. By that logic reversing the construction of the array should result in the private tele to be kept by _.uniq instead of the public one, no? 

If you think that's possibly a solution let me know and I'll create the pull request, I just don't want to be wasting your time if it's more complex than that.

**Comment by niekcandaele** [comment]
Hmm not quite, the `concat` method works like `a.concat(b)` => `[a, b]` ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

So the order of teles is already correct. You were close though, I believe the problem can be fixed in these lines: 

https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/63dfc17d0663e5695b7f608b6698769ae53340db/api/hooks/sdtdCommands/commands/tele.js#L37-L42


Currently, it will find the players own tele first and afterwards the public tele which will overwrite the `teleportFound` var. If that piece of code is refactored to return as soon as it finds a result, this issue would be solved. I think `Array#find` will work for this.

I could be wrong of course :smile: 

A PR would be very welcome, please feel free to ping me on Discord if you need any help getting started!
