### ISSUE TITLE
Issues with randNum and randList

### ISSUE THREAD

**Issue by killahpwnz** [CatalysmsServerManager/7-days-to-die-server-manager#518]
**Describe the bug**
I used to be able to run randList no problem, but lately I get an error in console in-game: "ERR: Ignoring the invalid entity [0]".

Command: mes -1270 3 632 0 @ ${randNum:2:83}

I've tried variations of this command, all with the same result.  randList gives me the same error. I'm not sure how/when it broke, as I didn't force update CSMM till tonight hoping it would fix the issue and it didn't.

**To Reproduce**
Run a mes command in-game console with randNum or randList.
or
Setup a custom command with the same.

**Expected behavior**
I expect the randNum and randList functions to work as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/59756122/104542896-fb7dd200-55e9-11eb-91b8-a5094dc61798.png)

**Desktop (please complete the following information if this is a problem on the CSMM web application):**

**7 days to die server info:**
Game version: Alpha 19.3 (b6) Compatibility Version: Alpha 19.3
Mod CSMM Patrons: 18.5
Mod Allocs command extensions: 20
Mod Allocs server fixes: 23
Mod Allocs MapRendering and Webinterface: 35
Mod Garage Door Rotation: 1.0

**Additional context**
No additional context observed in CSMM logs or 7DTD server logs.

**Comment by niekcandaele** [comment]
Thanks for the detailed report!

I think this was resolved on Discord already but I'll repeat here if anyone stumbles upon this later.

CSMM features like randNum, randList, variables, ... do not work in the ingame console. They only work in CSMM context like custom commands or hooks. It surprises me that you say this used to work because it can never have worked in the ingame console. 

randNum will work in custom commands though

![image](https://user-images.githubusercontent.com/22315101/104573537-4aad1c80-5655-11eb-8ac6-6c821bac3e05.png)
![image](https://user-images.githubusercontent.com/22315101/104573562-526cc100-5655-11eb-912e-c784516bf55b.png)

I'll close this issue because I think there's no issue here, respond back if there is :)
