### ISSUE TITLE
Have prefixname when sending say message to server from CSMM

### ISSUE THREAD

**Issue by jeppelykke** [CatalysmsServerManager/7-days-to-die-server-manager#80]
**Is your feature request related to a problem? Please describe.**
When using Server automation the tekst gets send like:
**Server: Text here from command line** 

**Describe the solution you'd like**
I would like to have a options to have a prefix botname for all communections from CSMM to the server. 

Exsample on server it will look like this: where it be LykkeBOT insted of server. 
LykkeBOT: To reguest admin help use: @admin message here

**Describe alternatives you've considered**
Using a 3rd party adminmod like ServerTools to send such messages.

**Comment by niekcandaele** [comment]
CSMM cannot touch that, it's a server-side API mod thing. What most users do is combine CSMM with an API mod. For example, with CPM you can use the say2 or pm2 command to achieve the functionality you want.


I do not want hard requirements on external mods in CSMM. This allows CSMM to work on different game versions easier. I also make it a point to allow users a high degree of customization like selecting commands to execute so that CSMM can work with any API mod.

Does that solve your need? :)

**Comment by jeppelykke** [comment]
It will have to do :) 

Thank you for the explanation, we will try work something out.
